# Generated by Django 5.1.4 on 2024-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crimeclue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField()),
                ('reported_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified as Real', 'Verified as Real'), ('Verified as Fake', 'Verified as Fake'), ('Counseling Approved', 'Counseling Approved'), ('Closed by Principal', 'Closed by Principal')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_year', models.CharField(blank=True, max_length=100, null=True)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
