# Generated by Django 5.1.4 on 2024-12-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='reported_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
