# Generated by Django 5.1.4 on 2024-12-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0004_crimereport_forwarded_to_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified as Real', 'Verified as Real'), ('Verified as Fake', 'Verified as Fake'), ('Forwarded to Principal', 'Forwarded to Principal'), ('Counseling Approved', 'Counseling Approved'), ('Closed by Principal', 'Closed by Principal')], default='Pending', max_length=50),
        ),
    ]
