# Generated by Django 5.1.4 on 2024-12-25 06:16

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0006_psychologist_remove_crimereport_investigation_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_reports', to='clue.crimereport')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clue.psychologist')),
            ],
        ),
    ]
