# Generated by Django 5.1.4 on 2024-12-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0007_council_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='principal_action_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='principal_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified as Real', 'Verified as Real'), ('Verified as Fake', 'Verified as Fake'), ('Forwarded to Principal', 'Forwarded to Principal'), ('Counseling Approved', 'Counseling Approved'), ('Closed by Principal', 'Closed by Principal'), ('Warning', 'Warning'), ('Suspended', 'Suspended'), ('Dismissed', 'Dismissed')], default='Pending', max_length=50),
        ),
    ]
