# Generated by Django 5.1.4 on 2024-12-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0008_crime_principal_action_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
