# Generated by Django 5.1.4 on 2024-12-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0009_alter_psychologist_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(default=100)),
                ('names', models.CharField(max_length=50)),
            ],
        ),
    ]
