# Generated by Django 5.1.4 on 2024-12-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0010_studentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='culprit_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='culprit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
