# Generated by Django 5.1.4 on 2024-12-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0011_crime_culprit_class_crime_culprit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
