# Generated by Django 5.1.4 on 2024-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0012_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlog',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='studentlog',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
